### ISSUE TITLE
"Inline local variable" produces broken code with JLS >= 1.8

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.ui#1552]
Follow up from See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2536.

Found while analyzing test failure of `org.eclipse.jdt.ui.tests.refactoring.InlineTempTests.test31()` in https://download.eclipse.org/eclipse/downloads/drops4/I20240725-1800/testresults/html/org.eclipse.jdt.ui.tests.refactoring_ep433I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

The test worked with the project compliance set to 1.4 or 1.5 (not sure which was used in the hierarchy of the test).
With the project compliance 1.8 inline refactoring of `emptyMap` variable produces compilation error at line

**In**
```
import java.util.Collections;
import java.util.Map;

class A extends Sup<String> {
	public A(Map<String, Integer> map) {
		Map<String, Integer> emptyMap= Collections.emptyMap(/*nada*/);
		method(emptyMap);
		method2(emptyMap);
		method3(emptyMap);
		new A(emptyMap);
		super.sup(emptyMap);
		
		Map<String, Integer> emptyMap2= emptyMap;
		emptyMap2= emptyMap;
		Object o= emptyMap;
		Map<? extends String, ?> emptyMap3= emptyMap;
		
		Integer first= emptyMap.values().iterator().next();
	}

	void method(Map<String, Integer> map) { }
	void method2(Map<? extends String, ?> map) {	}
	void method3(Object map) {	}
}

class Sup<S> {
	<A extends S, B> void sup(Map<A, B> map) {}
}
```

**Out after "inline local variable"**
```
import java.util.Collections;
import java.util.Map;

class A extends Sup<String> {
	public A(Map<String, Integer> map) {
		method(Collections.emptyMap(/*nada*/));
		method2(Collections.emptyMap(/*nada*/));
		method3(Collections.emptyMap(/*nada*/));
		new A(Collections.emptyMap(/*nada*/));
		super.sup(Collections.emptyMap(/*nada*/));
		
		Map<String, Integer> emptyMap2= Collections.emptyMap(/*nada*/);
		emptyMap2= Collections.emptyMap(/*nada*/);
		Object o= Collections.emptyMap(/*nada*/);
		Map<? extends String, ?> emptyMap3= Collections.emptyMap(/*nada*/);
		
		Integer first= Collections.emptyMap(/*nada*/).values().iterator().next(); // <----- ERROR here
	}

	void method(Map<String, Integer> map) { }
	void method2(Map<? extends String, ?> map) {	}
	void method3(Object map) {	}
}

class Sup<S> {
	<A extends S, B> void sup(Map<A, B> map) {}
}
```

**Comment by iloveeclipse** [comment]
@jjohnstn : could you please check?

**Comment by jjohnstn** [comment]
@iloveeclipse Was off Friday.  Will take a look at it.

**Comment by jjohnstn** [comment]
@iloveeclipse What is happening is that the type parameters for the emptyMap() call are not being copied in the inline.  The refactoring does a precheck to make sure no problems are introduced by the change by compiling the new CU.  I could not find any new code that seems to be doing erasure so IMO, it probably is an AST or rewriteAST change that is failing to copy the type parameters of the MethodInvocation.  I saw a similar problem with InlineTempConstants in the error report where it was due to type parameters missing.

**Comment by jjohnstn** [comment]
@iloveeclipse More info.  The problem is that the MethodBinding for the emptyMap() call is not marking that the type is in inferred from expected type.  The original call is:

`		Map<String, Integer> emptyMap= Collections.emptyMap(/*nada*/);`

There is a method DefaultBindingResolver.isResolvedTypeInferredFromExpectedType() that the MethodInvocation.isResolvedTypeInferredFromExpectedType() method calls.  This is called by Invocations.isResolvedTypeInferredFromExpectedType() which is called by the Refactoring code to determine if the MethodInvocation needs to have parameter types added.

I am not familiar with the jdt.core code that would have changed this, but I'll try.  If any compiler folks (@datho7561 ??) can find what changed, please feel free to speak up.
